FROM centos:7

RUN rpm -Uvh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm \
        && yum -y install zabbix-agent \
        && sed -i 's/Server=127.0.0.1/Server=10.178.0.9/g' /etc/zabbix/zabbix_agentd.conf \
        && sed -i 's/ServerActive=127.0.0.1/ServerActive=10.178.0.9/g' /etc/zabbix/zabbix_agentd.conf

EXPOSE 10050/TCP
CMD ["/usr/sbin/zabbix_agentd", "--foreground", "-c", "/etc/zabbix/zabbix_agentd.conf"]
